<?php
$z[0]=Array("global","",81,111);
$z[0][4]['name']="cfg_description";
$z[1]=Array("global","",149,176);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("include","",183,218);
$z[2][4]['filename']="head.htm";
$z[3]=Array("global","",316,342);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",385,422);
$z[4][4]['filename']="header.htm";
$z[5]=Array("include","",428,465);
$z[5][4]['filename']="banner.htm";
$z[6]=Array("type","\r\n				<a class=\"item\" href=\"[field:typelink/]\">\r\n					<i class=\"icon icon-facialmakeup\"></i>\r\n					<div class=\"content\">\r\n						<h2 class=\"title\">[field:typename/]</h2>\r\n						<h4 class=\"title_sub\">不一样的传统感受创新体验</h4>\r\n					</div>\r\n				</a>\r\n			",621,922);
$z[6][4]['typeid']="1";
$z[7]=Array("type","\r\n				<a class=\"item\" href=\"[field:typelink/]\">\r\n					<i class=\"icon icon-pen\"></i>\r\n					<div class=\"content\">\r\n						<h2 class=\"title\">[field:typename/]</h2>\r\n						<h4 class=\"title_sub\">不一样的传统感受创新体验</h4>\r\n					</div>\r\n				</a>\r\n			",929,1221);
$z[7][4]['typeid']="2";
$z[8]=Array("type","\r\n				<a class=\"item\" href=\"[field:typelink/]\">\r\n					<i class=\"icon icon-pen\"></i>\r\n					<div class=\"content\">\r\n						<h2 class=\"title\">[field:typename/]</h2>\r\n						<h4 class=\"title_sub\">不一样的传统感受创新体验</h4>\r\n					</div>\r\n				</a>\r\n			",1228,1520);
$z[8][4]['typeid']="6";
$z[9]=Array("type","\r\n				<a class=\"item\" href=\"[field:typelink/]\">\r\n					<i class=\"icon icon-logo\"></i>\r\n					<div class=\"content\">\r\n						<h2 class=\"title\">[field:typename/]</h2>\r\n						<h4 class=\"title_sub\">不一样的传统感受创新体验</h4>\r\n					</div>\r\n				</a>\r\n			",1527,1820);
$z[9][4]['typeid']="3";
$z[10]=Array("type","\r\n				<a class=\"item\" href=\"[field:typelink/]\">\r\n					<i class=\"icon icon-we\"></i>\r\n					<div class=\"content\">\r\n						<h2 class=\"title\">[field:typename/]</h2>\r\n						<h4 class=\"title_sub\">不一样的传统感受创新体验</h4>\r\n					</div>\r\n				</a>\r\n			",1827,2118);
$z[10][4]['typeid']="4";
$z[11]=Array("include","",3094,3131);
$z[11][4]['filename']="footer.htm";

?>