<?php
$z[0]=Array("global","",81,111);
$z[0][4]['name']="cfg_description";
$z[1]=Array("global","",149,176);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("include","",183,218);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",233,252);
$z[3][4]['name']="title";
$z[4]=Array("global","",253,279);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("include","",322,359);
$z[5][4]['filename']="header.htm";
$z[6]=Array("field","",523,544);
$z[6][4]['name']="content";
$z[7]=Array("type","\r\n		<a href=\"[field:typelink/]\" class=\"link triangle triangle_r\" alt=\"[field:typename/]\" title=\"[field:typename/]\"></a>\r\n	",633,789);
$z[7][4]['typeid']="6";
$z[8]=Array("type","\r\n		<a href=\"[field:typelink/]\" class=\"link triangle triangle_l\" alt=\"[field:typename/]\" title=\"[field:typename/]\"></a>\r\n	",794,950);
$z[8][4]['typeid']="4";

?>