<?php
$z[0]=Array("global","",182,212);
$z[0][4]['name']="cfg_description";
$z[1]=Array("global","",250,277);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("include","",284,319);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",334,353);
$z[3][4]['name']="title";
$z[4]=Array("global","",354,380);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("include","",423,460);
$z[5][4]['filename']="header.htm";
$z[6]=Array("include","",516,557);
$z[6][4]['filename']="nav_crumbs.htm";
$z[7]=Array("list","\r\n        <li class=\"mod_list\">\r\n            <div class=\"wrap\">\r\n                <div class=\"cover\">\r\n                    <img src=\"[field:cover/]\" alt=\"[field:title/]\" class=\"img\">\r\n                </div>\r\n                <div class=\"fr\">\r\n                    <h2 class=\"title\" title=\"[field:title/]\">[field:title/]</h2>\r\n                    <span class=\"wire\"></span>\r\n                    <p class=\"info\">[field:description/]</p>\r\n                    <div class=\"tr\">\r\n                        <a class=\"u_btn btn_more\" href=\"[field:arcurl/]\" target=\"_blank\">阅读更多</a>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n        </li>\r\n        ",633,1398);
$z[7][4]['addfields']="body,cover";
$z[7][4]['channelid']="1";
$z[7][4]['pagesize']="6";
$z[7][4]['orderby']="pubdate";
$z[8]=Array("pagelist","",2006,2084);
$z[8][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2149,2186);
$z[9][4]['filename']="footer.htm";

?>