<?php
$z[0]=Array("global","",78,108);
$z[0][4]['name']="cfg_description";
$z[1]=Array("global","",145,172);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("include","",178,213);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",226,245);
$z[3][4]['name']="title";
$z[4]=Array("global","",246,272);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("include","",311,348);
$z[5][4]['filename']="header.htm";
$z[6]=Array("include","",399,440);
$z[6][4]['filename']="nav_crumbs.htm";
$z[7]=Array("list","\n        <li class=\"mod_list\">\n            <div class=\"wrap\">\n                <div class=\"cover\">\n                    <img src=\"[field:cover/]\" alt=\"[field:title/]\" class=\"img\">\n                </div>\n                <div class=\"fr\">\n                    <h2 class=\"title\" title=\"[field:title/]\">[field:title/]</h2>\n                    <span class=\"wire\"></span>\n                    <p class=\"info\">[field:description/]</p>\n                    <div class=\"tr\">\n                        <a class=\"u_btn btn_more\" href=\"[field:arcurl/]\" target=\"_blank\">&gt;&gt;&gt;</a>\n                    </div>\n                </div>\n            </div>\n        </li>\n        ",511,1260);
$z[7][4]['addfields']="body,cover";
$z[7][4]['channelid']="1";
$z[7][4]['pagesize']="6";
$z[7][4]['orderby']="pubdate";
$z[8]=Array("pagelist","",1356,1434);
$z[8][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[8][4]['listsize']="4";
$z[9]=Array("type","\n		<a href=\"[field:typelink/]\" class=\"link triangle triangle_r\" alt=\"[field:typename/]\" title=\"[field:typename/]\"></a>\n	",1550,1704);
$z[9][4]['typeid']="1";
$z[10]=Array("type","\n		<a href=\"[field:typelink/]\" class=\"link triangle triangle_l\" alt=\"[field:typename/]\" title=\"[field:typename/]\"></a>\n	",1708,1862);
$z[10][4]['typeid']="6";

?>