</ul>
    <!-- E mod_list_wrap -->

    <!-- S page -->
    <div class="mod_page">
        <!-- <a href="#" class="mod_page_item">&lt;&lt;</a>
        <a href="#" class="mod_page_item" rel="prev">&lt;</a>
        <a href="#" class="mod_page_item active">1</a>
        <a href="#" class="mod_page_item">2</a>
        <a href="#" class="mod_page_item">3</a>
        <a href="#" class="mod_page_item">4</a>
        <a href="#" class="mod_page_item">5</a>
        <a href="#" class="mod_page_item" rel="next">&gt;</a>
        <a href="#" class="mod_page_item">&gt;&gt;</a> -->

        {dede:pagelist listitem="info,index,end,pre,next,pageno,option" listsize="5"