<li class="mod_list">
            <div class="wrap">
                <div class="cover">
                    <img src="[field:cover/]" alt="[field:title/]" class="img">
                </div>
                <div class="fr">
                    <h2 class="title" title="[field:title/]">[field:title/]</h2>
                    <span class="wire"></span>
                    <p class="info">[field:description/]</p>
                    <div class="tr">
                        <a class="u_btn btn_more" href="[field:arcurl/]">阅读更多</a>
                    </div>
                </div>
            </div>
        </li>