<?php
$z[0]=Array("global","",182,212);
$z[0][4]['name']="cfg_description";
$z[1]=Array("global","",250,277);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("include","",284,319);
$z[2][4]['filename']="head.htm";
$z[3]=Array("global","",417,443);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",485,522);
$z[4][4]['filename']="header.htm";
$z[5]=Array("include","",572,613);
$z[5][4]['filename']="nav_crumbs.htm";
$z[6]=Array("field","",731,750);
$z[6][4]['name']="title";
$z[7]=Array("field","",1017,1035);
$z[7][4]['name']="body";
$z[8]=Array("likearticle","\r\n				<a href=\"[field:arcurl/]\" class=\"item\" target=\"_blank\">\r\n					<div class=\"img_wrap\">\r\n						<img src=\"[field:cover/]\" alt=\"[field:title/]\" class=\"img\" title=\"[field:title/]\">\r\n					</div>\r\n					<h3 class=\"title\">[field:title/]</h3>\r\n				</a>\r\n				",1637,1965);
$z[8][4]['row']="4";
$z[8][4]['titlelen']="30";
$z[8][4]['mytypeid']="1";
$z[9]=Array("include","",3090,3127);
$z[9][4]['filename']="footer.htm";

?>