<?php
$z[0]=Array("img","\r\n",0,163);
$z[0][4]['itemname']="图片（推荐尺寸 0x0）";
$z[0][4]['autofield']="1";
$z[0][4]['notsend']="0";
$z[0][4]['type']="img";
$z[0][4]['isnull']="true";
$z[0][4]['islist']="1";
$z[0][4]['default']="";
$z[0][4]['maxlength']="250";
$z[0][4]['page']="";
$z[1]=Array("img_cover","\r\n",166,345);
$z[1][4]['itemname']="图片（推荐尺寸 0x0）";
$z[1][4]['autofield']="1";
$z[1][4]['notsend']="0";
$z[1][4]['type']="imgfile";
$z[1][4]['isnull']="true";
$z[1][4]['islist']="1";
$z[1][4]['default']="";
$z[1][4]['maxlength']="250";
$z[1][4]['page']="";

?>