<?php
$z[0]=Array("img_cover","\r\n",0,185);
$z[0][4]['itemname']="图片（推荐尺寸 1920x1000）";
$z[0][4]['autofield']="1";
$z[0][4]['notsend']="0";
$z[0][4]['type']="imgfile";
$z[0][4]['isnull']="true";
$z[0][4]['islist']="1";
$z[0][4]['default']="";
$z[0][4]['maxlength']="250";
$z[0][4]['page']="";
$z[1]=Array("link","\r\n",188,338);
$z[1][4]['itemname']="图片地址";
$z[1][4]['autofield']="1";
$z[1][4]['notsend']="0";
$z[1][4]['type']="text";
$z[1][4]['isnull']="true";
$z[1][4]['islist']="0";
$z[1][4]['default']="";
$z[1][4]['maxlength']="500";
$z[1][4]['page']="";

?>