<?php
$z[0]=Array("global","",209,239);
$z[0][4]['name']="cfg_description";
$z[1]=Array("global","",275,302);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",946,978);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1023,1055);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1102,1134);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1179,1211);
$z[5][4]['name']="cfg_templets_skin";

?>