<?php
$z[0]=Array("global","",182,212);
$z[0][4]['name']="cfg_description";
$z[1]=Array("global","",250,277);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("include","",284,319);
$z[2][4]['filename']="head.htm";
$z[3]=Array("global","",417,443);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",486,523);
$z[4][4]['filename']="header.htm";
$z[5]=Array("include","",529,566);
$z[5][4]['filename']="banner.htm";
$z[6]=Array("type","\r\n				<a class=\"item\" href=\"[field:typelink/]\">\r\n					<i class=\"icon icon-facialmakeup\"></i>\r\n					<div class=\"content\">\r\n						<h2 class=\"title\">[field:typename/]</h2>\r\n						<h4 class=\"title_sub\">不一样的传统感受创新体验</h4>\r\n					</div>\r\n				</a>\r\n			",722,1023);
$z[6][4]['typeid']="1";
$z[7]=Array("type","\r\n				<a class=\"item\" href=\"[field:typelink/]\">\r\n					<i class=\"icon icon-pen\"></i>\r\n					<div class=\"content\">\r\n						<h2 class=\"title\">[field:typename/]</h2>\r\n						<h4 class=\"title_sub\">不一样的传统感受创新体验</h4>\r\n					</div>\r\n				</a>\r\n			",1030,1322);
$z[7][4]['typeid']="2";
$z[8]=Array("type","\r\n				<a class=\"item\" href=\"[field:typelink/]\">\r\n					<i class=\"icon icon-logo\"></i>\r\n					<div class=\"content\">\r\n						<h2 class=\"title\">[field:typename/]</h2>\r\n						<h4 class=\"title_sub\">不一样的传统感受创新体验</h4>\r\n					</div>\r\n				</a>\r\n			",1329,1622);
$z[8][4]['typeid']="3";
$z[9]=Array("type","\r\n				<a class=\"item\" href=\"[field:typelink/]\">\r\n					<i class=\"icon icon-we\"></i>\r\n					<div class=\"content\">\r\n						<h2 class=\"title\">[field:typename/]</h2>\r\n						<h4 class=\"title_sub\">不一样的传统感受创新体验</h4>\r\n					</div>\r\n				</a>\r\n			",1629,1920);
$z[9][4]['typeid']="4";
$z[10]=Array("include","",2896,2933);
$z[10][4]['filename']="footer.htm";

?>