<?php
$z[0]=Array("global","",182,212);
$z[0][4]['name']="cfg_description";
$z[1]=Array("global","",250,277);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("include","",284,319);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",334,353);
$z[3][4]['name']="title";
$z[4]=Array("global","",354,380);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("include","",423,460);
$z[5][4]['filename']="header.htm";
$z[6]=Array("include","",574,611);
$z[6][4]['filename']="footer.htm";

?>